/**
 * \file
 *
 * \brief User board configuration template
 *
 */
/*
 * Support and FAQ: visit <a href="https://www.microchip.com/support/">Microchip Support</a>
 */

#ifndef CONF_BOARD_H
#define CONF_BOARD_H

#define TEMP1    IOPORT_CREATE_PIN(PORTA, 6)
#define TEMP2    IOPORT_CREATE_PIN(PORTA, 5)
#define TEMP3    IOPORT_CREATE_PIN(PORTA, 4)
#define TEMP4    IOPORT_CREATE_PIN(PORTA, 3)
#define TEMP5    IOPORT_CREATE_PIN(PORTA, 2)
#define TEMP6    IOPORT_CREATE_PIN(PORTA, 1)

#define TOUCH_XL    IOPORT_CREATE_PIN(PORTB, 0)
#define TOUCH_YU    IOPORT_CREATE_PIN(PORTB, 1)
#define TOUCH_XR    IOPORT_CREATE_PIN(PORTB, 2)
#define TOUCH_YD    IOPORT_CREATE_PIN(PORTB, 3)

#define LCD_CS		    IOPORT_CREATE_PIN(PORTC, 0)
#define LCD_DC		    IOPORT_CREATE_PIN(PORTC, 1)
#define LCD_RESET       IOPORT_CREATE_PIN(PORTC, 2)
#define LCD_BACKLIGHT   IOPORT_CREATE_PIN(PORTC, 4)
#define MOSI            IOPORT_CREATE_PIN(PORTC, 5)
#define MISO            IOPORT_CREATE_PIN(PORTC, 6)
#define SCK             IOPORT_CREATE_PIN(PORTC, 7)

#define AC_CONTROL1   IOPORT_CREATE_PIN(PORTD, 0)
#define AC_CONTROL2   IOPORT_CREATE_PIN(PORTD, 1)
#define AC_CONTROL3   IOPORT_CREATE_PIN(PORTD, 2)
#define AC_CONTROL4   IOPORT_CREATE_PIN(PORTD, 3)
#define AC_CONTROL5   IOPORT_CREATE_PIN(PORTD, 4)
#define AC_CONTROL6   IOPORT_CREATE_PIN(PORTD, 5)
#define DC_CONTROL1   IOPORT_CREATE_PIN(PORTD, 6)
#define DC_CONTROL2   IOPORT_CREATE_PIN(PORTD, 7)

#define SDA           IOPORT_CREATE_PIN(PORTE, 0)
#define SDL           IOPORT_CREATE_PIN(PORTE, 1)
#define DC_CONTROL3   IOPORT_CREATE_PIN(PORTE, 2)

#endif // CONF_BOARD_H
